# Generated by Django 3.2 on 2023-07-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=40)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=40)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=40)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.CharField(blank=None, default='Nom', max_length=50)),
                ('nom', models.CharField(blank=None, default='Nom', max_length=50)),
                ('prenom', models.CharField(blank=None, default='Prénom', max_length=50)),
                ('image', models.ImageField(default='images/blogs/blog.jpg', null=True, upload_to='images/agent/')),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Category', to='op.category')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Category', to='op.departement')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Category', to='op.direction')),
            ],
        ),
    ]
