# Generated by Django 3.2 on 2023-07-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0003_alter_bonus_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='facture',
            field=models.ImageField(blank=True, null=True, upload_to='images/factures/'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='valeur_deduite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
