# Generated by Django 3.2 on 2023-07-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_auto_20230701_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cuid',
            field=models.CharField(blank=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
