# Generated by Django 3.2 on 2023-07-01 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('op', '0006_alter_bonus_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='agent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Category', to='op.agent'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='check',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='facture',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/factures/'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='partenaire',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='valeur_deduite',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
