# Generated by Django 3.2 on 2023-07-01 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0007_auto_20230701_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='slug',
        ),
    ]
