# Generated by Django 3.2 on 2023-07-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0008_remove_agent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='check_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
            preserve_default=False,
        ),
    ]
