# Generated by Django 3.2 on 2023-07-01 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('op', '0010_alter_bonus_check_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Bonus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='agent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agent_Bonus', to='op.agent'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='partenaire',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Partenaire_Bonus', to=settings.AUTH_USER_MODEL),
        ),
    ]
