# Generated by Django 3.2 on 2023-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0011_auto_20230701_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mail',
            field=models.EmailField(blank=None, default=1, max_length=254),
            preserve_default=False,
        ),
    ]
